# -*- coding: utf-8 -*-
"""BadImages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kLWUJT2wluu2F0b2l3w4XjDUN-J2LlRw

Code for checking bad images, which, if not dealt with, would lead to interruption of the training of the model
"""

from PIL import Image
import os, sys

path = (r'/content/images_directory/')

dirs = os.listdir(path)

for item in dirs:
    try:

      Image.open(os.path.join(path,item)) # open the image file

    except (IOError, SyntaxError) as e:
      print('bad file')
      os.remove(path+item)