# -*- coding: utf-8 -*-
"""ResizingOpenCV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kLWUJT2wluu2F0b2l3w4XjDUN-J2LlRw

Code for resizing images using OpenCV. OpenCV is a better choice for resizing images as it keeps the exif data of the image in account.
"""

import cv2,os

path = '/content/kiss_detection/not_kissing/'
dirs = os.listdir(path)
i = 0

for im in dirs:

  oriimg = cv2.imread(path+im,cv2.IMREAD_COLOR)
  h, w, depth = oriimg.shape
  w1 = 500
  h1 = int(500*(h/w))
  new_img = cv2.resize(oriimg,(w1,h1))
  new_name = str(i)+ 'not_kisstest.jpeg'
  cv2.imwrite('/content/kiss_test_resized/not_kissing/'+new_name,new_img)
  i = i+1